//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_projec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Booking
    {
        public decimal PNR_No { get; set; }
        public Nullable<decimal> User_Id { get; set; }
        public Nullable<decimal> Train_No { get; set; }
        public Nullable<double> TotalFare { get; set; }
        public Nullable<System.DateTime> Booking_time_date { get; set; }
        public string tktstatus { get; set; }
    
        public virtual TrainDetail TrainDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
